In [2]:
import numpy as np
array=np.arange(20)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
array.shape

(20,)

In [4]:
# to check dimension of array

In [5]:
# Access element
array[3]

3

In [6]:
#Filling data using numpy
np.zeros((2,4))
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
np.random.random((2,3))


array([[0.99719344, 0.92899981, 0.1934652 ],
       [0.62181669, 0.83039368, 0.33083012]])

In [9]:
import numpy as np

a = np.array(10)
b = np.array([1,1,1,1])
c = np.array([[1, 1, 1], [2,2,2]])
d = np.array([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [10]:
import numpy as np

arr = np.array([1, 1, 1, 1, 1], ndmin=10)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[[[[[[1 1 1 1 1]]]]]]]]]]
number of dimensions : 10


In [11]:
import numpy as np
arr=([1,2,5,6,7])
arr[3]

6